apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-app-binding
  namespace: node-app
subjects:
- kind: ServiceAccount
  name: node-app-sa
  namespace: node-app
roleRef:
  kind: Role
  name: node-app-role
  apiGroup: rbac.authorization.k8s.io
